name: Build Executables

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        include:
          - os: ubuntu-22.04
            artifact_name: biblio-linux
            executable_extension: ""

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        modules: 'qtmultimedia'

    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev
        sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev
        sudo apt-get install -y libasound2-dev libpulse-dev
        sudo apt-get install -y libfuse2


    - name: Configure CMake
      run: |
        cd biblio
        cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cd biblio
        cmake --build build --config Release

    - name: Prepare Release Payload
      run: |
        mkdir -p release_payload
        cp biblio/build/biblio release_payload/biblio
        # Assuming 'assets' is in 'biblio/assets' relative to the project root
        cp -r biblio/assets release_payload/assets

    - name: Upload Release Payload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-artefacts
        path: release_payload/

  release:
    if: github.event_name == 'release'
    needs: build # Add dependency on the build job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Qt
      id: install_qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.3'
        host: 'linux'
        target: 'desktop'
        modules: 'qtmultimedia'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev
        sudo apt-get install -y libglu1-mesa-dev freeglut3-dev mesa-common-dev
        sudo apt-get install -y libasound2-dev libpulse-dev
        sudo apt-get install -y libfuse2
        # Install additional tools for better library bundling
        sudo apt-get install -y patchelf binutils
        # Install linuxdeployqt to workspace root
        wget -O linuxdeployqt https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
        chmod +x linuxdeployqt

    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: release-artefacts
        path: artifact_payload

    - name: Package Application
      env:
        QT_BIN_DIR: ${{ steps.install_qt.outputs.binPath }}
      run: |
        mkdir -p app_package
        cp artifact_payload/biblio app_package/biblio 
        cp -r artifact_payload/assets app_package/assets
        
        # First, check initial dependencies
        echo "--- Initial dependencies before bundling ---"
        ldd app_package/biblio
        echo "-------------------------------"
        
        # Run linuxdeployqt with more aggressive bundling
        ./linuxdeployqt app_package/biblio -qmake="$QT_BIN_DIR/qmake" -bundle-non-qt-libs -no-translations -no-copy-copyright-files -verbose=2 -always-overwrite
        
        # Manually copy additional libraries that might not be detected
        mkdir -p app_package/lib
        
        # Copy OpenCV libraries explicitly
        for lib in $(ldd app_package/biblio | grep opencv | awk '{print $3}'); do
          if [ -f "$lib" ]; then
            cp "$lib" app_package/lib/
            echo "Copied OpenCV library: $lib"
          fi
        done
        
        # Copy other system libraries that might be missing
        for lib in $(ldd app_package/biblio | grep -E "(libGL|libglut|libasound|libpulse)" | awk '{print $3}'); do
          if [ -f "$lib" ] && [ ! -f "app_package/lib/$(basename "$lib")" ]; then
            cp "$lib" app_package/lib/
            echo "Copied system library: $lib"
          fi
        done
        
        # Check dependencies after bundling
        echo "--- Dependencies after bundling ---"
        ldd app_package/biblio | grep "not found" || echo "All dependencies found"
        echo "--- All dependencies ---"
        ldd app_package/biblio
        echo "-------------------------------"
        
        echo "--- Listing bundled libraries ---"
        if [ -d "app_package/lib" ]; then
          ls -alh app_package/lib/
        else
          echo "No 'lib' directory created."
        fi
        echo "-------------------------------"
        
        # Create improved launcher script
        echo '#!/bin/bash' > app_package/run.sh
        echo 'SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)' >> app_package/run.sh
        echo 'cd "$SCRIPT_DIR"' >> app_package/run.sh
        echo '# Set library path to include bundled libraries' >> app_package/run.sh
        echo 'export LD_LIBRARY_PATH="./lib:$LD_LIBRARY_PATH"' >> app_package/run.sh
        echo '# Also set Qt plugin path if Qt plugins are bundled' >> app_package/run.sh
        echo 'if [ -d "./plugins" ]; then' >> app_package/run.sh
        echo '  export QT_PLUGIN_PATH="./plugins:$QT_PLUGIN_PATH"' >> app_package/run.sh
        echo 'fi' >> app_package/run.sh
        echo './biblio "$@"' >> app_package/run.sh
        chmod +x app_package/run.sh
        
        tar -czf biblio-linux.tar.gz -C app_package .

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          biblio-linux.tar.gz # Updated path: tarball is now in the workspace root
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
